### ISSUE TITLE
Improve the handling of (yet) unknown pseudo-classes

### ISSUE THREAD

**Issue by SelenIT** [HugoGiraudel/selectors-explained#12]
https://github.com/HugoGiraudel/selectors-explained/blob/ae890de7368c24cd4539834d9a358d62b6e5249b/src/parse/index.js#L13

Currently, it seems that all selector components starting with a single colon but not listed among the known pseudo-classes are treated as pseudo-elements. Wouldn't it be better to treat them as invalid selectors instead, given that only 4 known pseudo-elements from CSS2 can be legitimately written with `:` instead of `::`?

**Comment by KittyGiraudel** [comment]
This is fixed. :)
