### ISSUE TITLE
Create public deploy

### ISSUE THREAD

**Issue by pedrorijo91** [HugoGiraudel/selectors-explained#14]
Very cool project :) really useful.

Have you thought of creating a deployed version with public URL (using free heroku, netfly, or any other thing) ?

**Comment by Kilian** [comment]
It's here: https://hugogiraudel.github.io/selectors-explained/

**Comment by pedrorijo91** [comment]
oh, sorry, cool. maybe it could be added to the repo description or README? :)

**Comment by KittyGiraudel** [comment]
It is in the README. ;)
