### ISSUE TITLE
Invalid processing of case-sensitive/insensitive attribute selectors

### ISSUE THREAD

**Issue by Semigradsky** [HugoGiraudel/selectors-explained#15]
https://www.w3.org/TR/selectors-4/#attribute-case

```css
[frame=hsides i]
```
![image](https://user-images.githubusercontent.com/1198848/76207848-990cb600-620f-11ea-841a-29fba71033d4.png)

```css
[type="a" s]
```
![image](https://user-images.githubusercontent.com/1198848/76207815-8abe9a00-620f-11ea-8e2c-7ec66508f826.png)

**Comment by KittyGiraudel** [comment]
I guess this is not supported by https://www.npmjs.com/package/css-selector-parser.

**Comment by Semigradsky** [comment]
How about https://github.com/postcss/postcss-selector-parser? It is more used and has better support.

**Comment by IlyaStreltsynTR** [comment]
Or https://github.com/csstree/csstree, which also has separate token types for pseudo-class and pseudo-element selectors and more

**Comment by KittyGiraudel** [comment]
I changed the parser for https://github.com/fb55/css-what#readme which is solid. It doesn’t support `s` but it does support `i` so I’m going to mark this as closed. :)
