### ISSUE TITLE
doesn't vs code have this feature anyway or is this just a coding skill challenge?

### ISSUE THREAD

**Issue by godalming123** [HugoGiraudel/selectors-explained#19]
when you hover over a CSS for a few seconds selector vs code will tell you what it means.

**Comment by KittyGiraudel** [comment]
I think it’s a little different:
<img width="734" alt="Screenshot 2021-03-01 at 20 02 18" src="https://user-images.githubusercontent.com/1889710/109545362-1092bf80-7ac9-11eb-84e6-86cb164b1b03.png">

Also not everyone uses VSC, especially when starting web development. :)
