### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by avigoldman** [HugoGiraudel/selectors-explained#21]
Hey, looks like when I try to visit https://hugogiraudel.github.io/selectors-explained/ it doesn't work anymore.

**Comment by KittyGiraudel** [comment]
It moved: https://kittygiraudel.github.io/selectors-explained/.

Edit: I updated the link set in the GitHub repo details. Thanks!

**Comment by avigoldman** [comment]
Gotcha, thanks!
