### ISSUE TITLE
Consider parsing attribute values and use them in explanation

### ISSUE THREAD

**Issue by polarbirke** [HugoGiraudel/selectors-explained#4]
**Example:** 
`img[alt=""]`

**Current explanation:**
An `<img>` element with an attribute `alt`.

**Could be:**
An `<img>` element with an _empty_ `alt` attribute.

**Comment by KittyGiraudel** [comment]
Fixed with https://github.com/HugoGiraudel/selectors-explained/commit/2e200772947c5a6f562bdabf7f247c56ef0ec9fc. Thank you!

**Comment by polarbirke** [comment]
Nice, that was quick! 🚀
